### ISSUE TITLE
Supported input range?

### ISSUE THREAD

**Issue by iljah** [juppiega/IL2017#2]
I couldn't find information about what range of parameters are supported as input for IL2017 subroutine. Are there any geographical restrictions? What altitudes are supported/tested/make sense?

**Comment by juppiega** [comment]
Good question. 

The geophysical variation of the training data covers the observed variability from the 1980s to early 2010s (multiple solar cycles, many super-storms). 

Main restriction indeed comes from the altitude coverage of the observational data; all data below 200 km is daytime; the mass density observations don't go below 230 km, nor are they available above 530 km. There are some Helium observations from above 600 km, but these are near solar maximum. 300 to 500 km is the optimal range, with the most complete geophysical and geographical coverage. 

Here's the altitude-distribution of the composition and total mass density data (x-axis is the WGS84 altitude):
![hist_alt_comp](https://user-images.githubusercontent.com/7830631/60180385-eebe4100-97ed-11e9-89c2-8a4cb3ed90c5.png)
![hist_alt_total](https://user-images.githubusercontent.com/7830631/60180398-f382f500-97ed-11e9-8c8e-01d5c478a82a.png)

**Comment by iljah** [comment]
Thanks, what range would be sensible for F30 and its average?

**Comment by juppiega** [comment]
The density observations cover the range from 40 to 150 for both.
