### ISSUE TITLE
Start date and time of AE_integrals?

### ISSUE THREAD

**Issue by iljah** [juppiega/IL2017#3]
Looks like AE integral timestamps are in days so they would start from around beginning of this millenia assuming current calendar and first day of year, but does 0 mean year 0 or year 1? Or when does the data end, 2016-12-31T23:59Z?

**Comment by juppiega** [comment]
Day 1 is 1st of January on year 0, so the data runs from 01-01-2001 to 31-Dec-2015 23:57:00. You can use Octave's "datestr" function to get a human-readable version of the dates: e.g. datestr(timestamps(1))

**Comment by iljah** [comment]
Thanks, according to https://www.mathworks.com/help/matlab/ref/datenum.html this format starts from 0000-00-00(T00:00:00). Python doesn't seem to consider year 0 as valid but I can reproduce the correct last date (excluding the extra microsecond) with
```
>>> datetime(1,1,1)+timedelta(days=7.3632999791666667e+05)-timedelta(days=367)
datetime.datetime(2015, 12, 31, 23, 57, 0, 1)
```

**Comment by iljah** [comment]
I don't know why I have to substract 367 days but I'll assume it works also for earlier timestamps...
